# new-shelf-scanner-admin/.github/workflows/deploy.yml
name: Deploy Admin App to Firebase Hosting

on:
  push:
    branches:
      - main # Or your preferred deployment branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: ./new-shelf-scanner-admin # ** Make sure this is the correct directory for your admin app **

      - name: Build Admin App
        run: npm run build
        working-directory: ./new-shelf-scanner-admin # ** Make sure this is the correct directory for your admin app **

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEW_SHELF_SCANNER }}" # ** Replace with your GitHub Secret name **
          projectId: "YOUR_FIREBASE_PROJECT_ID" # ** Replace with your Firebase Project ID **
          target: "your-hosting-target" # ** Optional: Specify a hosting target if you have multiple sites **
          entryPoint: "./new-shelf-scanner-admin" # ** Make sure this is the correct directory for your admin app **
        env:
          # Pass environment variables needed for the build process (e.g., Firebase config)
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_ADMIN_API_KEY }}
          # Add other Firebase config variables as needed
